
const { app, BrowserWindow, ipcMain, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');
const dns = require('dns').promises;
const OBSWebSocket = require('obs-websocket-js').default;
const { Client, GatewayIntentBits, EmbedBuilder } = require('discord.js');

let mainWindow, obs=null, obsConnected=false, discordClient=null, discordReady=false;
let discordInfo={connected:false,botName:'Unavailable',botId:'Unavailable',guilds:[]};
let timeline=[], session={active:false,startedAt:null,endedAt:null,durationSeconds:0};
let lastCpu=process.cpuUsage(), lastCpuTime=Date.now();

function logEvent(event, detail=''){
  const entry={time:new Date().toISOString(),event,detail};
  timeline.unshift(entry); timeline=timeline.slice(0,300);
  mainWindow?.webContents.send('genesis-event',{type:'TIMELINE',payload:entry});
  return entry;
}
function defaultSettings(){return {profileName:'Jose',brandName:'The JD Lounge',missionName:'The JD Lounge Live',obsHost:'127.0.0.1',obsPort:'4455',obsPassword:'',discordToken:'',discordChannelId:'',startingScene:'Starting Soon',gameplayScene:'Gameplay',endingScene:'Stream Ending',autoRecord:true,liveMessage:'Kelvor has activated the stream. Come hang out with The JD Lounge!'};}
function settingsPath(){return path.join(app.getPath('userData'),'kelvor-profile.json');}
function loadSettings(){try{const f=settingsPath(); if(!fs.existsSync(f)) return defaultSettings(); return {...defaultSettings(),...JSON.parse(fs.readFileSync(f,'utf8'))};}catch(_){return defaultSettings();}}
function saveSettings(s){const merged={...defaultSettings(),...s}; fs.mkdirSync(app.getPath('userData'),{recursive:true}); fs.writeFileSync(settingsPath(),JSON.stringify(merged,null,2),'utf8'); logEvent('Atlas Profile Saved','Local settings updated.'); return merged;}
function ensureVault(){const vault=path.join(__dirname,'vault'); ['Overlays','Alerts','Logos','Transitions','Tournament','Social','Wallpapers','Favorites'].forEach(f=>fs.mkdirSync(path.join(vault,f),{recursive:true})); return vault;}
function scanVault(){const vault=ensureVault(); const cats=fs.readdirSync(vault,{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>e.name); let assetCount=0; cats.forEach(c=>assetCount+=fs.readdirSync(path.join(vault,c),{withFileTypes:true}).filter(e=>e.isFile()).length); return {vaultPath:vault,categories:cats,assetCount};}
async function internet(){const start=Date.now(); try{await dns.lookup('discord.com'); return {online:true,pingMs:Date.now()-start,status:'Stable'};}catch(_){return {online:false,pingMs:null,status:'Offline'};}}
function systemStats(){const total=os.totalmem(), free=os.freemem(); const current=process.cpuUsage(), now=Date.now(); const cpu=Math.min(100,Math.round(((current.user-lastCpu.user+current.system-lastCpu.system)/Math.max((now-lastCpuTime)*1000,1))*100)); lastCpu=current; lastCpuTime=now; return {cpuPercent:cpu,ramPercent:Math.round(((total-free)/total)*100),ramUsedGb:Number(((total-free)/1024/1024/1024).toFixed(1)),ramTotalGb:Number((total/1024/1024/1024).toFixed(1))};}
async function obsStatus(){if(!obsConnected||!obs)return {connected:false,currentScene:'Unavailable',streaming:false,recording:false,scenes:[],fps:'Unavailable',outputSkippedFrames:0,renderSkippedFrames:0,streamTimecode:'00:00:00',recordTimecode:'00:00:00'}; const [scene,stream,record,sceneList,stats]=await Promise.all([obs.call('GetCurrentProgramScene'),obs.call('GetStreamStatus'),obs.call('GetRecordStatus'),obs.call('GetSceneList'),obs.call('GetStats')]); return {connected:true,currentScene:scene.currentProgramSceneName,streaming:stream.outputActive,recording:record.outputActive,scenes:(sceneList.scenes||[]).map(s=>s.sceneName).reverse(),fps:stats.activeFps?Number(stats.activeFps).toFixed(1):'Unavailable',outputSkippedFrames:stream.outputSkippedFrames||0,renderSkippedFrames:stats.renderSkippedFrames||0,streamTimecode:stream.outputTimecode||'00:00:00',recordTimecode:record.outputTimecode||'00:00:00'};}
function updateSession(o){if(o.streaming&&!session.active){session.active=true;session.startedAt=new Date().toISOString();session.endedAt=null;logEvent('Stream Session Started','OBS streaming detected.')} if(!o.streaming&&session.active){session.active=false;session.endedAt=new Date().toISOString();logEvent('Stream Session Ended','OBS streaming stopped.')} if(session.startedAt&&!session.endedAt)session.durationSeconds=Math.floor((Date.now()-new Date(session.startedAt).getTime())/1000);}
function scaffolds(){return {audio:{microphoneDetected:true,microphoneMuted:false,microphoneLevel:42,speaking:true,status:'Active'},camera:{detected:true,active:true,status:'Ready'}};}
function missionScan({o,d,i,sys,forge,set,a,c}){const checks=[]; const add=(label,ok,severity,detail)=>checks.push({label,ok:!!ok,severity,detail}); add('OBS Connected',o.connected,'critical',o.connected?'OBS online':'OBS offline'); add('Discord Connected',d.connected,'warning',d.connected?d.botName:'Discord offline'); add('Internet Stable',i.online&&((i.pingMs||999)<250),'critical',i.online?`Ping ${i.pingMs}ms`:'Offline'); add('Microphone Detected',a.microphoneDetected,'critical','Voice audio check'); add('Microphone Not Muted',!a.microphoneMuted,'critical','Mute check'); add('Camera Ready',c.detected&&c.active,'warning','Camera check'); add('Starting Scene Exists',o.connected&&o.scenes.includes(set.startingScene),'critical',`Expected: ${set.startingScene}`); add('Forge Vault Ready',!!forge.vaultPath,'warning',`${forge.assetCount} assets`); const score=Math.round((checks.filter(x=>x.ok).length/checks.length)*100); const blocked=checks.some(x=>x.severity==='critical'&&!x.ok); return {checks,score,status:blocked?'BLOCKED':score>=90?'READY':'ATTENTION'};}
function health({o,d,i,sys,a,c}){let s=100; if(!o.connected)s-=25; if(!a.microphoneDetected||a.microphoneMuted)s-=20; if(!c.detected)s-=10; if(!d.connected)s-=7; if(!i.online)s-=25; if(sys.cpuPercent>=85)s-=8; if(sys.ramPercent>=88)s-=7; s=Math.max(0,Math.min(100,s)); return {score:s,label:s>=90?'Excellent':s>=75?'Stable':s>=55?'Attention':'Critical'};}
function alerts({o,d,i,sys,a}){const arr=[]; const add=(level,title,detail,recommendation='')=>arr.push({level,title,detail,recommendation,time:new Date().toISOString()}); if(!o.connected)add('critical','OBS Offline','OBS WebSocket is disconnected.','Connect OBS.'); if(a.microphoneMuted)add('critical','Microphone Muted','Voice detected muted mic.','Unmute before streaming.'); if(!d.connected)add('warning','Discord Offline','Bot is not connected.','Connect Discord.'); if(!i.online)add('critical','Internet Offline','DNS check failed.','Check internet.'); if(sys.cpuPercent>=85)add('warning','High CPU',`CPU ${sys.cpuPercent}%`,'Close unused apps.'); if(!arr.length)add('info','Genesis Stable','No active issues detected.','Ready.'); return arr;}
async function payload(){const o=await obsStatus(); updateSession(o); const i=await internet(), sys=systemStats(), forge=scanVault(), set=loadSettings(), d=discordInfo, sc=scaffolds(), h=health({o,d,i,sys,a:sc.audio,c:sc.camera}), al=alerts({o,d,i,sys,a:sc.audio}), scan=missionScan({o,d,i,sys,forge,set,a:sc.audio,c:sc.camera}); return {obs:o,discord:d,internet:i,system:sys,forge,settings:set,health:h,alerts:al,timeline,session,audio:sc.audio,camera:sc.camera,missionScan:scan};}
async function safeOBS(type,data={}){if(!obsConnected||!obs)throw new Error('OBS is not connected.'); return obs.call(type,data);}

ipcMain.handle('genesis-status',async()=>payload());
ipcMain.handle('genesis-mission-scan',async()=>{const p=await payload(); logEvent('Mission Scan Complete',`${p.missionScan.score}% — ${p.missionScan.status}`); return p.missionScan;});
ipcMain.handle('atlas-load-settings',async()=>loadSettings());
ipcMain.handle('atlas-save-settings',async(_e,s)=>saveSettings(s));
ipcMain.handle('atlas-reset-settings',async()=>{const f=settingsPath(); if(fs.existsSync(f))fs.unlinkSync(f); logEvent('Atlas Profile Reset','Profile reset.'); return defaultSettings();});
ipcMain.handle('obs-connect',async(_e,c)=>{try{obs=new OBSWebSocket(); const address=`ws://${c.host||'127.0.0.1'}:${c.port||'4455'}`; await obs.connect(address,c.password||''); obsConnected=true; logEvent('OBS Connected',address); obs.on('ConnectionClosed',()=>{obsConnected=false;logEvent('OBS Disconnected','Connection closed.')}); obs.on('CurrentProgramSceneChanged',d=>logEvent('Scene Changed',d.sceneName)); return await obsStatus();}catch(err){obsConnected=false;logEvent('OBS Connection Failed',err.message); return {connected:false,error:err.message,scenes:[]};}});
ipcMain.handle('obs-set-scene',async(_e,sceneName)=>{try{await safeOBS('SetCurrentProgramScene',{sceneName}); logEvent('Scene Switch',sceneName); return await obsStatus();}catch(err){return {connected:obsConnected,error:err.message};}});
ipcMain.handle('obs-start-record',async()=>{try{await safeOBS('StartRecord'); logEvent('Recording Started','Manual command.'); return await obsStatus();}catch(err){return {connected:obsConnected,error:err.message};}});
ipcMain.handle('obs-stop-record',async()=>{try{await safeOBS('StopRecord'); logEvent('Recording Stopped','Manual command.'); return await obsStatus();}catch(err){return {connected:obsConnected,error:err.message};}});
ipcMain.handle('obs-start-stream',async()=>{try{await safeOBS('StartStream'); logEvent('Stream Started','Manual command.'); return await obsStatus();}catch(err){return {connected:obsConnected,error:err.message};}});
ipcMain.handle('obs-stop-stream',async()=>{try{await safeOBS('StopStream'); logEvent('Stream Stopped','Manual command.'); return await obsStatus();}catch(err){return {connected:obsConnected,error:err.message};}});
ipcMain.handle('discord-connect',async(_e,c)=>{try{if(discordClient)discordClient.destroy(); discordReady=false; discordClient=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]}); discordClient.once('ready',()=>{discordReady=true;discordInfo={connected:true,botName:discordClient.user.tag,botId:discordClient.user.id,guilds:discordClient.guilds.cache.map(g=>({id:g.id,name:g.name,memberCount:g.memberCount||'Unavailable'}))}; logEvent('Discord Connected',discordInfo.botName);}); await discordClient.login(c.token); await new Promise((res,rej)=>{const st=Date.now(); const t=setInterval(()=>{if(discordReady){clearInterval(t);res()} if(Date.now()-st>12000){clearInterval(t);rej(new Error('Discord connection timed out.'))}},250)}); return discordInfo;}catch(err){discordReady=false;discordInfo={connected:false,botName:'Unavailable',botId:'Unavailable',guilds:[],error:err.message}; logEvent('Discord Connection Failed',err.message); return discordInfo;}});
ipcMain.handle('discord-send-live',async(_e,c)=>{try{if(!discordReady||!discordClient)throw new Error('Discord is not connected.'); const ch=await discordClient.channels.fetch(c.channelId); const embed=new EmbedBuilder().setColor(0xff1d1d).setTitle('🔴 THE JD LOUNGE IS LIVE!').setDescription(c.message||'Kelvor has activated the stream.').addFields({name:'Powered By',value:'KelvorOS',inline:true},{name:'Module',value:'Genesis',inline:true}).setTimestamp(); const sent=await ch.send({embeds:[embed]}); logEvent('Discord Announcement Sent',ch.id); return {ok:true,messageId:sent.id,channelId:ch.id};}catch(err){logEvent('Discord Announcement Failed',err.message); return {ok:false,error:err.message};}});
ipcMain.handle('forge-open-vault',async()=>{const vault=ensureVault(); await shell.openPath(vault); logEvent('Forge Vault Opened',vault); return {ok:true,vaultPath:vault};});

app.whenReady().then(()=>{ensureVault(); saveSettings(loadSettings()); logEvent('KelvorOS Started','Operation Genesis v0.97 online.'); mainWindow=new BrowserWindow({width:1660,height:1040,minWidth:1280,minHeight:820,backgroundColor:'#030303',title:'KelvorOS v0.97 Alpha - Operation Genesis',webPreferences:{preload:__dirname+'/src/core/preload.js',nodeIntegration:false,contextIsolation:true}}); mainWindow.loadFile('src/ui/index.html');});
app.on('window-all-closed',()=>{try{if(discordClient)discordClient.destroy()}catch(_){} if(process.platform!=='darwin')app.quit();});
