const { app, BrowserWindow, ipcMain, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const os = require('os');
const dns = require('dns').promises;
const OBSWebSocket = require('obs-websocket-js').default;
const { Client, GatewayIntentBits, EmbedBuilder } = require('discord.js');
let mainWindow, obs=null, obsConnected=false, discordClient=null, discordReady=false;
let discordInfo={connected:false,botName:'Unavailable',botId:'Unavailable',guilds:[]};
let timeline=[]; let lastCpu=process.cpuUsage(); let lastCpuTime=Date.now();
function createWindow(){ mainWindow=new BrowserWindow({width:1640,height:1040,minWidth:1280,minHeight:820,backgroundColor:'#030303',title:'KelvorOS v0.91 Alpha - Operation Overwatch',webPreferences:{preload:__dirname+'/src/core/preload.js',nodeIntegration:false,contextIsolation:true}}); mainWindow.loadFile('src/ui/index.html'); }
function logEvent(event,detail=''){ const entry={time:new Date().toISOString(),event,detail}; timeline.unshift(entry); timeline=timeline.slice(0,250); mainWindow?.webContents.send('overwatch-event',{type:'TIMELINE',payload:entry}); return entry; }
function defaults(){return {profileName:'Jose',brandName:'The JD Lounge',obsHost:'127.0.0.1',obsPort:'4455',obsPassword:'',discordToken:'',discordChannelId:'',startingScene:'Starting Soon',gameplayScene:'Gameplay',endingScene:'Stream Ending',autoRecord:true,liveMessage:'Kelvor has activated the stream. Come hang out with The JD Lounge!'};}
function settingsPath(){return path.join(app.getPath('userData'),'kelvor-profile.json')}
function loadSettings(){try{let f=settingsPath(); if(!fs.existsSync(f)) return defaults(); return {...defaults(),...JSON.parse(fs.readFileSync(f,'utf8'))};}catch{return defaults();}}
function saveSettings(s){let m={...defaults(),...s}; fs.mkdirSync(app.getPath('userData'),{recursive:true}); fs.writeFileSync(settingsPath(),JSON.stringify(m,null,2),'utf8'); logEvent('Atlas Profile Saved','Local settings updated.'); return m;}
function ensureVault(){let v=path.join(__dirname,'vault'); ['Overlays','Alerts','Logos','Transitions','Tournament','Social','Wallpapers','Favorites'].forEach(folder=>{let p=path.join(v,folder); if(!fs.existsSync(p)) fs.mkdirSync(p,{recursive:true});}); return v;}
function scanVault(){let v=ensureVault(); let cats=fs.readdirSync(v,{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>e.name); let assetCount=0; cats.forEach(c=>assetCount+=fs.readdirSync(path.join(v,c),{withFileTypes:true}).filter(e=>e.isFile()).length); return {vaultPath:v,categories:cats,assetCount};}
async function getInternet(){let start=Date.now(); try{await dns.lookup('discord.com'); return {online:true,pingMs:Date.now()-start,status:'Stable'};}catch{return {online:false,pingMs:null,status:'Offline'};}}
function getSystem(){let total=os.totalmem(), free=os.freemem(); let ramPercent=Math.round(((total-free)/total)*100); let cur=process.cpuUsage(), now=Date.now(); let cpu=Math.min(100,Math.round(((cur.user-lastCpu.user+cur.system-lastCpu.system)/Math.max((now-lastCpuTime)*1000,1))*100)); lastCpu=cur; lastCpuTime=now; return {cpuPercent:cpu,ramPercent,ramUsedGb:+((total-free)/1073741824).toFixed(1),ramTotalGb:+(total/1073741824).toFixed(1),platform:os.platform(),cpuCores:os.cpus()?.length||0};}
async function obsStatus(){ if(!obsConnected||!obs) return {connected:false,currentScene:'Unavailable',streaming:false,recording:false,scenes:[],fps:'Unavailable',cpuUsage:'Unavailable',outputSkippedFrames:0,renderSkippedFrames:0,streamTimecode:'00:00:00',recordTimecode:'00:00:00'}; let [scene,stream,record,sceneList,stats]=await Promise.all([obs.call('GetCurrentProgramScene'),obs.call('GetStreamStatus'),obs.call('GetRecordStatus'),obs.call('GetSceneList'),obs.call('GetStats')]); return {connected:true,currentScene:scene.currentProgramSceneName,streaming:stream.outputActive,recording:record.outputActive,scenes:(sceneList.scenes||[]).map(s=>s.sceneName).reverse(),fps:stats.activeFps?Number(stats.activeFps).toFixed(1):'Unavailable',cpuUsage:stats.cpuUsage?Number(stats.cpuUsage).toFixed(1)+'%':'Unavailable',outputSkippedFrames:stream.outputSkippedFrames||0,renderSkippedFrames:stats.renderSkippedFrames||0,streamTimecode:stream.outputTimecode||'00:00:00',recordTimecode:record.outputTimecode||'00:00:00'};}
function alerts({obs,discord,internet,system}){let a=[]; const add=(level,title,detail,recommendation='')=>a.push({level,title,detail,recommendation,time:new Date().toISOString()}); if(!obs.connected)add('critical','OBS Offline','OBS WebSocket is not connected.','Open OBS and connect from Systems.'); if(obs.connected&&Number(obs.fps)<50)add('warning','Low OBS FPS',`OBS FPS is ${obs.fps}.`,'Check encoder and game performance.'); if(obs.outputSkippedFrames>0)add('warning','Dropped Frames Detected',`${obs.outputSkippedFrames} output skipped frames.`,'Lower bitrate or check internet.'); if(obs.renderSkippedFrames>0)add('warning','Render Skipped Frames',`${obs.renderSkippedFrames} render skipped frames.`,'Close heavy apps.'); if(!discord.connected)add('warning','Discord Offline','Discord bot is not connected.','Connect Discord before announcements.'); if(!internet.online)add('critical','Internet Offline','DNS check failed.','Check your connection.'); if(internet.online&&internet.pingMs>250)add('warning','High Network Latency',`Ping is ${internet.pingMs} ms.`,'Wait for network to stabilize.'); if(system.cpuPercent>=85)add('warning','High CPU Usage',`CPU is ${system.cpuPercent}%.`,'Close background apps.'); if(system.ramPercent>=88)add('warning','High RAM Usage',`RAM is ${system.ramPercent}%.`,'Close unused apps.'); if(!a.length)add('info','Stream Health Stable','No active issues detected.','Keep monitoring.'); return a;}
function health({obs,discord,internet,system}){let score=100; if(!obs.connected)score-=30; if(obs.connected&&Number(obs.fps)<50)score-=12; if(obs.outputSkippedFrames>0)score-=12; if(obs.renderSkippedFrames>0)score-=8; if(!discord.connected)score-=8; if(!internet.online)score-=30; if(internet.online&&internet.pingMs>250)score-=10; if(system.cpuPercent>=85)score-=10; if(system.ramPercent>=88)score-=8; score=Math.max(0,Math.min(100,score)); return {score,label:score>=90?'Excellent':score>=75?'Stable':score>=55?'Attention':'Critical'};}
async function payload(){let obs=await obsStatus(), internet=await getInternet(), system=getSystem(), forge=scanVault(), settings=loadSettings(), discord=discordInfo; return {obs,discord,internet,system,forge,settings,health:health({obs,discord,internet,system}),alerts:alerts({obs,discord,internet,system}),timeline};}
async function safeOBS(type,data={}){if(!obsConnected||!obs) throw new Error('OBS is not connected.'); return obs.call(type,data);}
ipcMain.handle('overwatch-status',async()=>payload()); ipcMain.handle('atlas-load-settings',async()=>loadSettings()); ipcMain.handle('atlas-save-settings',async(_,s)=>saveSettings(s)); ipcMain.handle('atlas-reset-settings',async()=>{let f=settingsPath(); if(fs.existsSync(f))fs.unlinkSync(f); logEvent('Atlas Profile Reset','Profile reset.'); return defaults();});
ipcMain.handle('obs-connect',async(_,config)=>{try{obs=new OBSWebSocket(); let address=`ws://${config.host||'127.0.0.1'}:${config.port||'4455'}`; await obs.connect(address,config.password||''); obsConnected=true; logEvent('OBS Connected',address); obs.on('ConnectionClosed',()=>{obsConnected=false;logEvent('OBS Disconnected','Connection closed.');mainWindow?.webContents.send('overwatch-event',{type:'OBS_DISCONNECTED'});}); obs.on('CurrentProgramSceneChanged',d=>{logEvent('Scene Changed',d.sceneName); mainWindow?.webContents.send('overwatch-event',{type:'OBS_SCENE_CHANGED',sceneName:d.sceneName});}); obs.on('StreamStateChanged',d=>{logEvent('Stream State',d.outputState||'Updated');}); obs.on('RecordStateChanged',d=>{logEvent('Recording State',d.outputState||'Updated');}); return await obsStatus();}catch(e){obsConnected=false; logEvent('OBS Connection Failed',e.message||String(e)); return {connected:false,error:e.message||String(e),scenes:[]};}});
ipcMain.handle('obs-set-scene',async(_,sceneName)=>{try{await safeOBS('SetCurrentProgramScene',{sceneName}); logEvent('Scene Switch Requested',sceneName); return await obsStatus();}catch(e){return {connected:obsConnected,error:e.message||String(e)}}});
ipcMain.handle('obs-start-record',async()=>{try{await safeOBS('StartRecord'); logEvent('Recording Started','Manual command.'); return await obsStatus();}catch(e){return {connected:obsConnected,error:e.message||String(e)}}});
ipcMain.handle('obs-stop-record',async()=>{try{await safeOBS('StopRecord'); logEvent('Recording Stopped','Manual command.'); return await obsStatus();}catch(e){return {connected:obsConnected,error:e.message||String(e)}}});
ipcMain.handle('obs-start-stream',async()=>{try{await safeOBS('StartStream'); logEvent('Stream Started','Manual command.'); return await obsStatus();}catch(e){return {connected:obsConnected,error:e.message||String(e)}}});
ipcMain.handle('obs-stop-stream',async()=>{try{await safeOBS('StopStream'); logEvent('Stream Stopped','Manual command.'); return await obsStatus();}catch(e){return {connected:obsConnected,error:e.message||String(e)}}});
ipcMain.handle('discord-connect',async(_,config)=>{try{if(discordClient){try{discordClient.destroy()}catch{}} discordReady=false; discordInfo={connected:false,botName:'Unavailable',botId:'Unavailable',guilds:[]}; discordClient=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]}); discordClient.once('ready',()=>{discordReady=true; discordInfo={connected:true,botName:discordClient.user.tag,botId:discordClient.user.id,guilds:discordClient.guilds.cache.map(g=>({id:g.id,name:g.name,memberCount:g.memberCount||'Unavailable'}))}; logEvent('Discord Connected',discordInfo.botName); mainWindow?.webContents.send('overwatch-event',{type:'DISCORD_CONNECTED',payload:discordInfo});}); await discordClient.login(config.token); await new Promise((res,rej)=>{let start=Date.now(); let t=setInterval(()=>{if(discordReady){clearInterval(t);res()} if(Date.now()-start>12000){clearInterval(t);rej(new Error('Discord connection timed out.'))}},250)}); return discordInfo;}catch(e){discordReady=false; discordInfo={connected:false,botName:'Unavailable',botId:'Unavailable',guilds:[],error:e.message||String(e)}; logEvent('Discord Connection Failed',e.message||String(e)); return discordInfo;}});
ipcMain.handle('discord-send-live',async(_,config)=>{try{if(!discordReady||!discordClient)throw new Error('Discord is not connected.'); if(!config.channelId)throw new Error('Channel ID is required.'); let channel=await discordClient.channels.fetch(config.channelId); if(!channel||!channel.isTextBased())throw new Error('Channel not found or is not text-based.'); let embed=new EmbedBuilder().setColor(0xff1d1d).setTitle('🔴 THE JD LOUNGE IS LIVE!').setDescription(config.message||'Kelvor has activated the stream. Come hang out with The JD Lounge!').addFields({name:'Powered By',value:'KelvorOS',inline:true},{name:'Module',value:'Operation Overwatch',inline:true}).setFooter({text:'The JD Lounge Command Center'}).setTimestamp(); let sent=await channel.send({embeds:[embed]}); logEvent('Discord Announcement Sent',channel.id); return {ok:true,messageId:sent.id,channelId:channel.id};}catch(e){logEvent('Discord Announcement Failed',e.message||String(e)); return {ok:false,error:e.message||String(e)}}});
ipcMain.handle('forge-open-vault',async()=>{let vault=ensureVault(); await shell.openPath(vault); logEvent('Forge Vault Opened',vault); return {ok:true,vaultPath:vault};});
app.whenReady().then(()=>{ensureVault(); saveSettings(loadSettings()); logEvent('KelvorOS Started','Operation Overwatch online.'); createWindow();});
app.on('window-all-closed',()=>{try{if(discordClient)discordClient.destroy()}catch{} if(process.platform!=='darwin')app.quit();});
